In [10]:
import pandas as pd
import csv

In [14]:
pd.read_csv("Inv_3CPC_loc_DE.csv", delimiter=";", low_memory=False).to_csv("Inv_3CPC_loc_DE_conv.csv", sep=",", quoting=csv.QUOTE_ALL)

In [13]:
pd.read_csv("Inv_3CPC_loc_DE_conv.csv", delimiter=",")

/tmp/ipykernel_581305/2705305078.py:1: DtypeWarning: Columns (3,8) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("Inv_3CPC_loc_DE_conv.csv", delimiter=",")

,Unnamed: 0,appln_id,appln_auth,appln_nr,appln_kind,appln_filing_date,appln_filing_year,appln_nr_epodoc,appln_nr_original,ipr_type,...,G99,H01,H02,H03,H04,H05,H99,Y02,Y04,Y10
0,0,151,EP,07024389,A,2007-12-17,2007,EP20070024389,07024389,PI,...,0,0,0,0,0,0,0,0,0,0
1,1,217,EP,08010186,A,2008-06-04,2008,EP20080010186,08010186,PI,...,0,0,0,0,0,0,0,0,0,0
2,2,218,EP,08010192,A,2008-06-04,2008,EP20080010192,08010192,PI,...,0,0,0,0,0,0,0,0,0,0
3,3,243,EP,08010251,A,2008-06-05,2008,EP20080010251,08010251,PI,...,0,1,0,0,0,0,0,1,0,0
4,4,266,EP,08010352,A,2008-06-06,2008,EP20080010352,08010352,PI,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239748,2239748,417932626,EP,14168297,A,2014-05-14,2014,EP20140168297,14168297,PI,...,0,0,0,0,1,0,0,0,0,0
2239749,2239749,417945890,US,201213676367,A,2012-11-14,2012,US201213676367,13676367,PI,...,0,0,0,0,1,0,0,0,0,0
2239750,2239750,410143413,EP,13004314,A,2013-09-03,2013,EP20130004314,13004314,PI,...,0,0,0,0,0,0,0,1,0,0
2239751,2239751,330264513,DE,102010045579,A,2010-09-16,2010,DE20101045579,102010045579,PI,...,0,0,0,0,1,0,0,0,0,0
2239752,2239752,330264537,DE,102009032642,A,2009-07-10,2009,DE20091032642,102009032642,PI,...,0,0,0,0,0,0,0,0,0,0